version: '3.2'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - .:/opt/www
    depends_on:
      - php
  php:
    build: ./docker/php-fpm
    volumes:
      - ./:/opt/www
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /opt/www
  mysql:
    build: ./docker/mysql
    volumes:
      - mysql_data/:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql_data:
